version: '2'
services:
  tmsapp-app:
    image: tmsapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://tmsapp-mysql:3306/tmsapp?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://tmsapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://tmsapp-elasticsearch:9200
    ports:
      - 8282:8282
  tmsapp-mysql:
    extends:
      file: mysql.yml
      service: tmsapp-mysql
  tmsapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: tmsapp-elasticsearch
